vnet_name           = "myVnet2"
address_space       = "10.4.0.0/16"
location            = "East US"
resource_group_name = "tfModeRG"
subnet_name         = "mySubnet"
subnet_prefix       = "10.4.1.0/24"
