vnet_name           = "myVnet"
address_space       = "10.3.0.0/16"
location            = "East US"
resource_group_name = "tfModeRG"
subnet_name         = "mySubnet"
subnet_prefix       = "10.3.1.0/24"
